### PR TITLE
add php 8 support

### LINKED ISSUE #64: PHP 8 support
Hey, will this library add PHP 8 support soon?

### PR DESCRIPTION
**Pull request by shokme**

### CODE REVIEW

**Comment by shokme** [comment]
Waiting [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4702) to be compatible with php 8.0

**Comment by dmyers** [comment]
Could you at least for now allow PHP 8 version in `composer.json` so I can update my application?

**Comment by curquiza** [comment]
Is this PR breaking for some users (php 8 users or PHP 7 users)? 🙂

**Comment by shokme** [comment]
We don't use any feature of php 8, so php 7 user can still use the package and we don't use any deprecated feature removed by php 8 it should be good.

**Review by curquiza — APPROVED** [review]
I'm ok with this then! Thanks for this PR! Feel free to merge when you want @shokme 🙂

**Comment by dmyers** [comment]
Thanks @shokme! 👍

**Pull request merged**
