### PR TITLE
Add documentation about faceted search

### PR DESCRIPTION
**Pull request by infostreams**

### CODE REVIEW

**Comment by infostreams** [comment]
Perhaps it's better to add this to the default functionality, somehow, but I wanted to share what I painstakingly figured out so that others might benefit from it. I want to use faceted search but it wasn't  mentioned in either the documentation or the source code, so I decided to make life a bit easier for those googlers who come after me.

**Comment by shokme** [comment]
Hey @infostreams 

Thank you for your contribution !

I'm not fan of the idea to add it as default functionality, because I want to keep the idea of Laravel Scout
>Laravel Scout provides a simple, driver based solution for adding full-text search to your Eloquent models.

Then, when I read your PR I think it will update meilisearch for every model imported (I will test).

But, I understand the problem of meilisearch not having a way to manage your indexes as algolia does. I'm not fan of self ad but if you were searching for a way to manage your indexes (more than just a facet search) -> https://github.com/shokme/meilisearch-dashboard

Edit: Perhaps you can have a CLI instead that takes the index name as args and then options to add your facet
```
php artisan scout:facets movies --facet=title,release_date
```

**Comment by infostreams** [comment]
Well, for me I want to use the power of Meilisearch without losing the ease-of-use of Laravel Scout. My code doesn't do anything unless you add a 'facets' property to your model. 

For my own code I prefer to do it like this because my searching code (how I invoke Meilisearch) will have to change as well. That means the facets definition needs to be part of the code base as well, otherwise that code will break, so I put them in a logical place - in the model itself.

I don't really have an opinion what you end up doing with this contribution. I do think it's a bit too verbose for the main README, perhaps it would be better suited for the Wiki, and then you can link to it from the README? Just a thought.

**Comment by shokme** [comment]
`ModelImported::class` is an event dispatch by scout when running `... scout:import ...`. This is not the best as if you have to update your facets it will re-import everything only for that, this is not good in my opinion.
Even using ModelObserver won't be efficient. I really suggest you to make a CLI, if you prefer define your facets,synonyms,.. inside your model you can make a CLI that will browse all your searchable model and update facets,synonyms,...

Again, Laravel Scout should not provide this functionality by default, you are free to add them but I won't make it a default,
because if we do it for facets, we will have to do the same for synonyms,distinct,stopwords,...
I understand your issue but that's not the purpose of scout.

I thank you for your contribution and I'm happy that you found a way to achieve your goal with Laravel Scout. But I won't accept this pr, sorry.

**Comment by infostreams** [comment]
Could you add some documentation somewhere as to how you can use facets with the scout driver? Thanks. I don't care if it's the default behavior or not, but facets are sold as a big feature of MeiliSearch and then you don't have any documentation about it in the Laravel driver anywhere. That's a bit weird.

**Comment by infostreams** [comment]
At the very least, could you open the wiki so that I can make a page there? It cost me 4 hours to research how to do this cleanly, how to use your product with your official plugin that is, and it would be a shame if it was all for nothing.

**Comment by shokme** [comment]
For the wiki you should ask @curquiza (I asked her)

I'm not against a wiki :smile: but how you have done shouldn't be how to do it. It works in your case but a little example:

I have 150 000 items to import it takes times to achieve, like 5 minutes. Then, I want to change how are handle my facets or later a new facets is coming only for new documents, I have to re-import 150 000 items only to update a settings.
because the only way to trigger the **ModelImported** event is by doing `php artisan scout:import "App\Models\Book"`
Then we should do the same for synonyms each time you made change for a facets you will also update you synonyms and your model will look like hell :stuck_out_tongue: 
Do you think it is normal ?

Now, what you have done is working and that's well for you :+1: but if I have to work with my set of data this is not efficient.
If you are ok with the idea of using a command, I can write you how I would handle it :wink: (but you already have done the whole job).

at the risk of repeating myself, Scout has been made to query document from Algolia, Algolia offer a GUI to setup your indexes, so yeah that's logic it cost you a lot of time to achieve what you wanted because it was not made to configure an index but to search against it.

PS: if you want to share your discovery and how **you** you want to handle it, you can also use dev.to / medium / etc :smile: that would be so cool !

**Comment by curquiza** [comment]
Hello @infostreams!

Thanks for your feedback about the documentation 🙂
As @shokme said, scout is indeed only a tool to manipulate documents and not the indexes. However, wiki pages could be really useful for the users, for example with a `How To` section to explain how to handle indexes, synonyms..etc

If the idea of a CLI is also interesting, I let you open an issue @shokme! 🙂

**Comment by infostreams** [comment]
Thanks for your replies. In the end, I am not really invested in this issue or project. It's your search engine, and it's your official Laravel Scout plugin. In my opinion, but that's just one opinion, you should focus on making all the awesome features of your awesome search engine as easy to use as humanly possible. I would expect ALL of the functionality mentioned in your [advanced guides](https://docs.meilisearch.com/guides/advanced_guides/) to be somehow exposed and documented in all of your plugins. That's a high level product decision though, not necessarily a documentation decision, and obviously it's a lot of work.

FWIW, the documentation changes I requested in this pull request didn't end up working for me. I now implement these changes in a database migration, as follows:

```php
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // make exercises searchable
        try { Artisan::call('scout:index', ['--delete', 'name'=>'exercise']); } catch (\Exception $e) { }

        Artisan::call('scout:index', ['name'=>'exercise']);
        Artisan::call('scout:import', ['model'=>'\\App\\Models\\Exercise']);

        Artisan::call('scout:flush', ['model'=>'\\App\\Models\\Exercise']);
        $model = new \App\Models\Exercise();
        app(\Laravel\Scout\EngineManager::class)
            ->driver('meilisearch')
            ->getIndex($model->searchableAs())
            ->updateAttributesForFaceting($model->facets);

        // make lessons searchable
        try { Artisan::call('scout:index', ['--delete', 'name'=>'lesson']); } catch (\Exception $e) { }

        Artisan::call('scout:index', ['name'=>'lesson']);
        Artisan::call('scout:import', ['model'=>'\\App\\Models\\Lesson']);

        Artisan::call('scout:flush', ['model'=>'\\App\\Models\\Lesson']);
        $model = new \App\Models\Lesson();
        app(\Laravel\Scout\EngineManager::class)
            ->driver('meilisearch')
            ->getIndex($model->searchableAs())
            ->updateAttributesForFaceting($model->facets);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        try { Artisan::call('scout:index', ['--delete', 'name'=>'exercise']); } catch (\Exception $e) { }
        try { Artisan::call('scout:index', ['--delete', 'name'=>'lesson']); } catch (\Exception $e) { }
    }
```

where I then make sure to list the facets I want in the appropriate model class, in a ```public $facets = [...]``` property.

Again, I'm leaving this here just in case someone ends up googling the terms and is at a complete loss as to how to do this. This is one way of doing it. There might be other ways. There might be better ways. I don't really know. I think it's within your problem space to find answers to these questions, because in the end I don't really care 🤷‍♂️ Thanks a bunch for Meilisearch and for the plugin! It's really an awesome piece of software, and I'm happy I got to contribute at least a little bit. Keep up the good work!

**Comment by infostreams** [comment]
One last thing: I think the configuration of indexes and facets should be part of the code base, and not managed separately through a command line tool (however useful that might be). The reason for this is that my code depends on how the index is configured. If it's misconfigured, it won't work properly. I also don't necessarily want to create a separate "installation" script or maintain separate documentation for when the software is installed in a new environment, or by a new developer. 

What you could do, obviously, is create some sort of artisan command (`php artisan meilisearch:install`?) which configures and imports the indexes for use with the software. It could read its configuration from a PHP file (or whatever) within the code base, so that you cannot misconfigure the indexes AND so that no-one has to maintain any documentation. Just a thought.

**Comment by curquiza** [comment]
Hello again @infostreams!

Thanks for your time describing your investigation, the solution you found and your feedback about your experience with this plugin. Be sure it will be helpful 🙂
All our SDKs/plugins (and of course the search-engine) are constently evolving and we try to do our best with them. Make the user experience as smooth as possible is one our main concern, even if, as you said, it's not always easy to do: it can lead to difficult decisions and it often implies a lot of works.
That's why I take notes about your not-really-good user experience and I opened an issue linking our discussion here (see #46). Be sure we are going to think about that with the documentation team. Decisions can make time to be implemented because we are a small team with a lot of tasks to do right now, but at least your feedback will not desapear 😉

I'm happy you enjoy using MeiliSearch, and of course I thank you for having contributed to this plugin! MeiliSearch would not be as good without its community. For example, this laravel-scout plugin is created and highly maintained by @shokme who is one of our most involved external contributors 🚀 All the MeiliSearch's team is really proud to build tools with its community. So, thanks again for being a part of it! 🙂

PS: If you are more interested in contributing to MeiliSearch tools, you can join us to [our Slack](https://meilicommunity.slack.com/join/shared_invite/zt-c4rs8tpi-ZId_q3fw~7cqeuzFG4XHaA#/) (I'm Clementine). It might be easier to discuss!

**Pull request closed without merging**
