### PR TITLE
get index or create it with the model primary key if not exist

### LINKED ISSUE #36: I can't index my documents (they are ok at Algolia)
I'm using Laravel 7, MS 0.13
I'm trying to index my model using:
`php artisan scout:import "App\Models\Product"
`
Then I do (local_product is my index):
`curl -X GET 'http://localhost:7700/indexes/local_product/documents'
`
And I get `[]`

If I index in Algolia, my documents are ok there.
Also if I index movies doing:
`curl   -X POST 'http://127.0.0.1:7700/indexes/movies/documents'   --data @movies.json
`
The movies are also indexed.

### PR DESCRIPTION
**Pull request by shokme**
Resolve #36

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hey @shokme 
Thanks for this new contribution! 
Could you add a test that tries `getOrCreateIndex` two times in a row on the same index ? Just to be sure it is working correctly when the index already exists.

Also, is the primary key optionnal ? Could you add a test without any primary key given?

**Comment by shokme** [comment]
> Could you add a test that tries getOrCreateIndex two times in a row on the same index ? Just to be sure it is working correctly when the index already exists.

`getOrCreateIndex` is from the sdk, usually I avoid to test thing already tested. Then, I don't know if this is possible to do with mocked test ?

> Also, is the primary key optionnal ? Could you add a test without any primary key given?

By default Laravel will set a `$primaryKey = id` in its model, each time a model is created/updated, even if the primary key is optional Laravel will always have it.

But, should we keep the possibility to create an index by using the cli ?
```sh
php artisan scout:index name -k optionalKey
```
if we are able to handle it automatically, I don't see this cli useful anymore (even If we have to keep a part of it to delete an index).

**Comment by bidoubiwa** [comment]
Ah yes, redundant tests are bad, you are right. 

> By default Laravel will set a $primaryKey = id in its model, each time a model is created/updated, even if the primary key is optional Laravel will always have it.

MeiliSearch infers the `id` when non is provided. In [the documentation it is said that](https://docs.meilisearch.com/guides/main_concepts/documents.html#setting-the-primary-key) 
> If no primary key has been given either when the index was created or as a parameter of the add documents route, the primary key will be searched in the first document sent.
MeiliSearch will search for an attribute that contains the string id in a case-insensitive manner (i.e, `uid`, `MovieId`, `ID`, `123id123`)

Does this mean that if I create a index with the laravel-scout it will enforce `id` as a primary key ? Meaning it removes the possibility that MeiliSearch infers for example `uid` as the primary key on document creation? 



> But, should we keep the possibility to create an index by using the cli ? 

I'm not enough aware of the use case of this SDK, I prefer waiting on @curquiza opinion on this

**Comment by elfeffe** [comment]
@bidoubiwa I think Meilisearch must not infer the ID in this case, it should use Laravel $primaryKey, which can or cannot include the string "id".
If I have a product, I think UPC to SKU can be the key, that's the reason why Laravel lets you set a $primaryKey.
In my opinion, the MS primary key should be the $primaryKey that you set in Laravel.
In fact, in some e-commerce project that I have created using Algolia, I use SKU as the primaryKey (foto24.com for example)

**Comment by shokme** [comment]
it will be less error prone to let laravel handle the PK of meilisearch as you can have a PK != \*id\*

**Review by curquiza — APPROVED** [review]
The MeiliSearch API will manage the automatic index creation in the future (https://github.com/meilisearch/MeiliSearch/issues/918), but until the official release, this is a great fix!

**Pull request merged**
