### PR TITLE
Add IndexCreated event when a new index is created

### PR DESCRIPTION
**Pull request by mmachatschek**
This adds the possibility to update a index when it is created. 

It is helpful e.g. when you have a model with fields that are essential for an output to work but not all fields should be searchable.

[Searchable Fields](https://docs.meilisearch.com/guides/advanced_guides/field_properties.html#searchable-fields)

A listener could then check the passed model or index name and if there exists another method on the model with the information about e.g. `displayFields`, then the index can be updated accordingly

E.g.:

```php
class Model
{
    public function toSearchableArray()
    {
        return [
            'id' => $this->id,
            'uuid' => $this->uuid,
            'name' => $this->name,
            'summary' => $this->summary,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
```

### CODE REVIEW

**Comment by shokme** [comment]
Hello @mmachatschek 

As I'm not a big user of meilisearch, I'm not able to see if this really useful even if I understand the interest of having such a thing.
But I think index configuration should be handle by an UI like Algolia does

I don't know @curquiza what does other libraries like the symfony one

My first goal with this package was to extend laravel scout possibilities to meilisearch and not allow more than what scout does
But since this package exists I have seen many people wanted this package to do more than its purpose.

**Comment by curquiza** [comment]
Hello @mmachatschek!
Thanks for your involvement in this repo, this is really appreciable! 😄

> My first goal with this package was to extend laravel scout possibilities to meilisearch and not allow more than what scout does

I agree with @shokme, this is not really the purpose of the laravel-scout plugin to add this kind of feature.

@shokme made a Wiki that helps users like you who want to update the index settings:
- https://github.com/meilisearch/meilisearch-laravel-scout/wiki/Indexes-settings-using-config-file
- https://github.com/meilisearch/meilisearch-laravel-scout/wiki/Indexes-settings-using-model

Thanks for this suggestion anyway :)

**Comment by mmachatschek** [comment]
@curquiza thanks for the comment on this one. I didn't see that the wiki has entries about this. Maybe there should be a bigger section about it in the readme. But anyway. I'll probably copy the suggestion of @shokme
Thanks :rocket:

**Comment by curquiza** [comment]
Yes you're right I'm going to update the README, and highlight it 😄

**Pull request closed without merging**
